/*!
 * 
 *   @aptero/axolotis-module-teams v1.0.0
 *
 *   Copyright (c) Aptero  and project contributors.
 *
 *   This source code is licensed under the undefined license found in the
 *   LICENSE file in the root directory of this source tree.
 *
 */
!function webpackUniversalModuleDefinition(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t(require("@aptero/axolotis-player")):"function"==typeof define&&define.amd?define("axolotis-module-teams",["@aptero/axolotis-player"],t):"object"==typeof exports?exports["axolotis-module-teams"]=t(require("@aptero/axolotis-player")):e["axolotis-module-teams"]=t(e["@aptero/axolotis-player"])}(self,(e=>(()=>{"use strict";var t={12:t=>{t.exports=e}},r={};function __webpack_require__(e){var o=r[e];if(void 0!==o)return o.exports;var i=r[e]={exports:{}};return t[e](i,i.exports,__webpack_require__),i.exports}__webpack_require__.n=e=>{var t=e&&e.__esModule?()=>e.default:()=>e;return __webpack_require__.d(t,{a:t}),t},__webpack_require__.d=(e,t)=>{for(var r in t)__webpack_require__.o(t,r)&&!__webpack_require__.o(e,r)&&Object.defineProperty(e,r,{enumerable:!0,get:t[r]})},__webpack_require__.o=(e,t)=>Object.prototype.hasOwnProperty.call(e,t),__webpack_require__.r=e=>{"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})};var o={};return(()=>{__webpack_require__.r(o),__webpack_require__.d(o,{AxItem:()=>AxItem,CHANGE_SETTINGS_URL:()=>s,MICROSOFT_SERVICE:()=>t,MICROSOFT_STATIC_SERVICE:()=>r,MSTEAMS_QUERY_PARAM:()=>_,PROCESS_DEEPLINK:()=>a,PROPERTIES_SERVICE:()=>i,msTeamsAPI:()=>msTeamsAPI,msTeamsAPILight:()=>msTeamsAPILight,msTeamsAPILightAsync:()=>msTeamsAPILightAsync,registerWithImport:()=>registerWithImport});var e=__webpack_require__(12);const t="@aptero/axolotis-module-teams/MicrosoftService",r="@aptero/axolotis-module-teams/MicrosoftStaticService",i="@aptero/axolotis-module-properties/Properties",s="ms-teams-change-settings-url",a="ms-teams-deep-link",_="msteams";function msTeamsAPILight(){return(0,e.getServiceSync)(r)}function msTeamsAPILightAsync(){return(0,e.getService)(r)}async function msTeamsAPI(){return(0,e.getService)(t)}class AxItem{constructor(e,t){this.moduleMicrosoftService=e,this.moduleMicrosoftStaticService=t,console.log("@aptero/axolotis-module-teams installed")}modules(){let e={};return e[t]=this.moduleMicrosoftService,e[r]=this.moduleMicrosoftStaticService,e}}const registerWithImport=(t,r)=>{const o=(0,e.getGlobalStorageValue)(e.GLOBAL_WORLDS_ENTITY,!1);if(!(o&&o.length>0))throw new Error("Axolotis World Needs to be initialized");(0,e.registerItem)(new AxItem(t,r))}})(),o})()));
//# sourceMappingURL=dist-index.js.map